map_type: costmap
# resolution: 0.02
# z_resolution: 0.02
# global_frame: /map
# robot_base_frame: base_link
publish_voxel_map: true

# Enable the following line if using the publishSTLToOctomap
static_map: true
map_topic: /projected_map
# origin_x: 0
# origin_y: 0
# origin_z: 0
lethal_cost_threshold: 50
# Bug in costmap_2d!
unknown_cost_value: 255
track_unknown_space: true
#footprint: [[-0.45, -0.45], [-0.45, 0.45], [0.45, 0.45], [0.45, -0.45]]
#footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.325, -0.325]]
#footprint: [[-0.35, -0.35], [-0.35, 0.35], [0.35, 0.35], [0.35, -0.35]]
# footprint: [[-0.385, -0.385], [-0.385, 0.385], [0.385, 0.385], [0.385, -0.385]]
# footprint_padding: 0.01
#inflation_radius: 0.47 #---> experiments were run with this.
inflation_radius: 0.57
#inflation_radius: 0.38
robot_radius: 0.15
# cost_scaling_factor: 10.0
